# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2221978872d7e1a21983ef2e068ee3488a00621fa28a578a97e6c2676b189258cfc6607d36f63bd0bcedd7b10ba7afffa55dbe60edbc5d9a46bd72c7747b9b51

test:
  secret_key_base: 1ab5e2088e074fb3867174c8fb8726bb10776cecf7d756151a4664ee086e050a33801b3b0a81eef4a302f66f931d09d90bf67e471fde3472a803db1c59de717e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
